In [1]:
from __future__ import print_function
import sys
import pandas as pd
import csv

In [31]:

df = pd.read_csv('curated_gene_disease_associations.tsv',low_memory=False, sep = "\t")
df.head()

,geneId,geneSymbol,DSI,DPI,diseaseId,diseaseName,diseaseType,diseaseClass,diseaseSemanticType,score,EI,YearInitial,YearFinal,NofPmids,NofSnps,source
0,1,A1BG,0.700,0.538,C0019209,Hepatomegaly,phenotype,C23;C06,Finding,0.30,1.000,2017.0,2017.0,1,0,CTD_human
1,1,A1BG,0.700,0.538,C0036341,Schizophrenia,disease,F03,Mental or Behavioral Dysfunction,0.30,1.000,2015.0,2015.0,1,0,CTD_human
2,2,A2M,0.529,0.769,C0002395,Alzheimer's Disease,disease,C10;F03,Disease or Syndrome,0.50,0.769,1998.0,2018.0,3,0,CTD_human
3,2,A2M,0.529,0.769,C0007102,Malignant tumor of colon,disease,C06;C04,Neoplastic Process,0.31,1.000,2004.0,2019.0,1,0,CTD_human
4,2,A2M,0.529,0.769,C0009375,Colonic Neoplasms,group,C06;C04,Neoplastic Process,0.30,1.000,2004.0,2004.0,1,0,CTD_human

In [32]:
columns = ['geneSymbol', 'diseaseId']
df = pd.DataFrame(df, columns=columns)

In [33]:
df = df.groupby('geneSymbol', as_index=False).agg(lambda x: ', '.join(set(x.dropna())))

In [34]:
df['AllGeneDiseaseCount'] = df.diseaseId.str.count("C")

In [35]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9703 entries, 0 to 9702
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   geneSymbol           9703 non-null   object
 1   diseaseId            9703 non-null   object
 2   AllGeneDiseaseCount  9703 non-null   int64
dtypes: int64(1), object(2)
memory usage: 227.5+ KB

,geneSymbol,diseaseId,AllGeneDiseaseCount
0,A1BG,"C0019209, C0036341",2
1,A2M,"C0023890, C0750900, C0011570, C0007102, C02423...",26
2,A2ML1,"C0587248, C0028326, C1275081, C0175704, C00298...",7
3,A4GALT,"C0343640, C0006413, C4721444",3
4,AAAS,"C0376358, C0271742, C0033578",3

In [36]:
df.to_csv('df_allGeneDiseases.csv', index=False)